name: Odds API Filter and Telegram Sender

on:
  schedule:
    - cron: "*/30 * * * *"  # Hər 30 dəqiqədə bir işləyəcək
  workflow_dispatch:

jobs:
  run-filter:
    runs-on: ubuntu-latest

    steps:
      - name: Kodları yüklə
        uses: actions/checkout@v3

      - name: Python quraşdır
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Asılılıqları quraşdır
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Filtr və Göndəriş
        run: python main.py
